version: '3.7'

networks:
  app-tier:
    driver: bridge

services:

  discordbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discordbot
    networks:
      - app-tier
    environment:
      - ProjectBToken=OTA4MDc4ODYyMTA4MzMyMDQy.YYwgWA.FF
    #   - ASPNETCORE_Kestrel__Certificates__Default__Password="Mirtaz95@#123" 
    #   - ASPNETCORE_Kestrel__Certificates__Default__Path=Library/Keychains/System.keychain/aspnetapp.pfx 
    ports:
      - 443:443
    # volumes:
    #   - ${HOME}/.aspnet/http/http